Name = input("Enter your Name:")
Surname = ("Mugiwara")
Enter_your_goal = input("Enter your goal : ")
print("welcome to the world of technology " + Name)
print("You are going to make history " + Surname)
print("You can achieve  your goal to  " +Enter_your_goal + " by regular Trainning")